version: "3"

services:
  nginx:
    container_name: parag_nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    ports:
      - 88:88
    volumes:
      - ./symfony/:/var/www/symfony
    environment:
      - VIRTUAL_HOST=paraglide
    networks:
      - paraglide

  php:
    container_name: parag_php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    environment:
      APP_ENV: dev
    volumes:
      - ./symfony/:/var/www/symfony
    networks:
      - paraglide

  postgres:
    container_name: parag_postgres
    image: postgres:11
    restart: always
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    networks:
      - paraglide
    volumes:
      - ./postgres/:/var/lib/postgresql/data

networks:
  paraglide:
    driver: bridge

volumes:
  paraglide:
    external: true