version: "3"

services:
  nginx:
    container_name: parag_nginx
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=paraglide
    networks:
      - paraglide

  php:
    container_name: parag_php
    build: ./
    restart: always
    volumes:
      - ./../:/var/www/html
    networks:
      - paraglide


  postgres:
    container_name: parag_postgres
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    networks:
      - paraglide
    volumes:
      - paraglide:/var/lib/postgresql/data

networks:
  paraglide:
    driver: bridge

volumes:
  paraglide:
    external: true