version: "3"

services:
  nginx:
    container_name: parag_nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./../:/var/www/html
      - ./nginx.conf:/etc/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=paraglide
    networks:
      - paraglide

  php:
    container_name: parag_php
    build: .
    volumes:
      - ./../:/var/www/html
    networks:
      - paraglide


  postgres:
    container_name: parag_postgres
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    networks:
      - paraglide

networks:
  paraglide:
    driver: bridge